version: '3'

services:
  nginx:
    container_name: lemp_nginx_dropcarbon
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    ports:
      - "80:80"

  php:
    container_name: lemp_php_dropcarbon
    image: peerasakp/php7-4
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    expose:
      - "9000"

  db:
    container_name: lemp_mariadb_dropcarbon
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    env_file:
      - ./mariadb/db.env
  
  phpmyadmin:
    container_name: lemp_phpmyadmin_dropcarbon
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
